### ISSUE TITLE
Database in bad state, Shoko Server unable to start

### ISSUE THREAD

**Issue by Truth-** [ShokoAnime/ShokoServer#780] opened 2019-04-09 18:55 UTC
## VERSION INFORMATION
Server Version: 3.9.3 and 3.9.4
Desktop Version: n/a

## LOG FILE
[https://pastebin.com/BxEcUPGp](https://pastebin.com/BxEcUPGp) (from v3.9.3.29629 docker cazzar/shokoserver:v3.9.3)
[https://pastebin.com/s2Dei8r6](https://pastebin.com/s2Dei8r6) (from v3.9.4.28311 docker cazzar/shokoserver:daily)

## DESCRIPTION
Shoko Server unable to start, unsure what cause the problem. I checked the log from when the problem occured and the latest thing the shokoserver was downloading banner images and then it suddenly stopped. 

I've tried recreating the docker container multiple times with different versions but i think the problem is with the Database as all tries result in the same error.

## STEPS TO REPRODUCE
Start the shoko server.
It fails.

**Comment by bigretromike** [comment] 2019-05-21 12:06
both log expired, btw.

**Comment by bigretromike** [comment] 2019-05-31 12:30
The best way is to not MIX ShokoServer version.
You can mix them if you have 2 separate databases, because of compatibility issues you can encounter (like this one - probably).

As the issue is old, logs expired I'm closing this one. 

If the issue is still present fell free to reopen issue and post current logs from current version of shokoserver.

**Closed by bigretromike** 2019-05-31 12:30 UTC
Labels: Bug - Major
