### ISSUE TITLE
Shows in WebUI (during manual link) are shown with Episode Numbers which are normal Episodes + Specials

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer#1047] opened 2023-03-13 20:01 UTC
## VERSION INFORMATION

Server Version: 837c647

WebUI Version: aa89c9c

## LOG FILE

nothing to see here

## DESCRIPTION
Conversation between @ElementalCrisis and myself regarding this

Baine — heute um 17:56 Uhr
also I'd be a big fan of indicating the actual number of eps, when selecting the show, and not all counted together
or something Like "1 (1)", meaning one episode, 1 special
just linked a movie and was confused because it showed 2 episodes for it
Elemental Crisis — heute um 17:57 Uhr
Movie?
Baine — heute um 17:57 Uhr
Given - The Movie (2020)
Elemental Crisis — heute um 17:57 Uhr
Sounds like a split movie
Baine — heute um 17:57 Uhr
nope
![image](https://user-images.githubusercontent.com/6566469/224817938-429e0af4-9d41-41e8-91b4-f84dff78d895.png)
![image](https://user-images.githubusercontent.com/6566469/224817996-72f53d2f-f633-482b-816e-fe2030386350.png)
Elemental Crisis — heute um 17:59 Uhr
I only see 1 "episode" for it.
Baine — heute um 17:59 Uhr
the above is in webui
Baine — heute um 17:59 Uhr
the below is on anidb

Old Desktop already makes the count more visible:
![image](https://user-images.githubusercontent.com/6566469/224818630-a7af77d7-6fd2-4bd6-9cab-e09e22b2ac0c.png)
![image](https://user-images.githubusercontent.com/6566469/224818787-55808449-522a-4dc4-b486-6530cfac7535.png)

## STEPS TO REPRODUCE

1. Have show, movie, whatever with normal episodes and specials
2. Try to add files to that show in the unrecognized utility in webui
3. be irritated by the difference in numbers

**Comment by revam** [comment] 2023-04-07 03:10
I'll look at it tomorrow.

**Comment by ElementalCrisis** [comment] 2023-04-07 03:47
Revisiting this issue, it's not a bug per say but a way the data is displayed. 

Currently, Desktop doesn't even show the count or type, just the name and AniDB ID. Web UI only shows the count and type if it has the info, otherwise it just shows a dash ``-`` instead. 

![image](https://user-images.githubusercontent.com/9443295/230536966-223da880-c982-4668-9fe6-8c52eff6d8bd.png)

We can either remove the count altogether or leave it how it is.

**Comment by revam** [comment] 2023-04-07 03:53
So we can just close it? Since i think we can show both the normal and special counts, provided we have the anidb entry locally, and also modify the anidb model to return them separately, since they exist separately and combined in the database and internal model.

**Comment by ElementalCrisis** [comment] 2023-04-07 04:22
I think the total count is fine, we can just make it show the total number of episodes.

**Closed** 2023-04-07 04:23 UTC
Labels: Enhancement - Feature Improvement
