### ISSUE TITLE
Trakt Returns 401

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#713] opened 2018-03-03 05:15 UTC
## VERSION INFORMATION

Server Version: 3.8.2
Desktop Version: 3.8.2

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

```
[2018-03-02 21:13:40:609] Error|ShokoServiceImplementation.EnterTraktPIN => TraktTVHelper.EnterTraktPIN => TraktTVHelper.SendData Error in SendData: 401 - System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Shoko.Server.Providers.TraktTV.TraktTVHelper.SendData(String uri, String json, String verb, Dictionary`2 headers, String& webResponse) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TraktTV\TraktTVHelper.cs:line 74
[2018-03-02 21:13:40:609] Error|ShokoServiceImplementation.EnterTraktPIN => TraktTVHelper.EnterTraktPIN => TraktTVHelper.SendData Error in SendData: {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

## DESCRIPTION

When attempting to authorize Trakt, Trakt returns a 401 with the above in the logfile.

## STEPS TO REPRODUCE

1, Get Trakt Token.
2. Attempt to authorize.

**Comment by Cazzar** [comment] 2018-03-03 11:16
We don't seem to follow the proper structure.... we are sending ```json
{
    "PINCode": "aaaabbbb"
}
```
not using the devicecode

**Comment by Cazzar** [comment] 2018-03-03 11:17
https://trakt.docs.apiary.io/#reference/authentication-oauth/generate-new-device-codes

**Comment by da3dsoul** [comment] 2018-03-21 15:22
Yeah cazzar asked me to look at it, but I've been busy and simply haven't wanted to, since I don't use trakt at all

**Comment by hidden4003** [comment] 2018-03-23 21:02
Well I just tried it from shoko desktop and it seemed to work, so I am not sure what kind of update needed here.

**Comment by hidden4003** [comment] 2018-03-26 08:49
@ElementalCrisis can you confirm or provide steps to reproduce? Is it the initial auth that fails or the re-auth after the first token expires?

**Comment by ElementalCrisis** [comment] 2018-03-26 09:15
They temporarily enabled the old auth way which is what we're currently using. However it's been depreciated and we need to use the new auth way as @Cazzar listed above.

**Comment by hidden4003** [comment] 2018-04-04 21:08
Should be fixed now.

**Closed** 2018-04-04 21:51 UTC
Labels: Bug - Minor
