### ISSUE TITLE
Linux-Container - Socket for AniDB UDP command is shut down

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer#662] opened 2017-08-30 14:27 UTC
## VERSION INFORMATION

Server Version: 
caeabf9512e8fc586b573a23db87b21b359372c5

Desktop Version: 
7c71dada1a1626e573d3a7ebebc5662c2df772da

## LOG FILE

```
[2017-08-30 14:19:35:399] Error|AniDBHelper.GetFileInfo => AniDBCommand_GetFileInfo.Process => AniDBUDPCommand.ProcessCommand System.Net.Sockets.SocketException (0x80004005): The socket has been shut down
  at System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEP) [0x00066] in <d2c057d9d34d4e029e580897bd60340c>:0
  at System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Net.EndPoint remoteEP) [0x00000] in <d2c057d9d34d4e029e580897bd60340c>:0
  at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand (System.Net.Sockets.Socket& soUDP, System.Net.IPEndPoint& remoteIpEndPoint, System.String sessionID, System.Text.Encoding enc) [0x001b4] in <d4afa1a68b524a69b4ed1b5f716c4313>:0
```

## DESCRIPTION

After running for a while (can't tell the exact amount of time), this starts showing in the logs,
resulting in failed anidb udp commands, and only a restart of shokoserver helps (only temporarily though)

## STEPS TO REPRODUCE

run shokoserver dockerized on linux
add import folder
run import

**Comment by da3dsoul** [comment] 2017-08-30 14:29
It's a mono issue. Nothing we can about it until it gets fixed in mono

**Comment by Cazzar** [comment] 2017-08-30 14:31
It also happens with non docker, I had it a lot, one person got it always
in docker and never in direct

**Comment by Baine** [comment] 2017-08-30 14:44
i also get this in direct, if that helps

**Comment by Cazzar** [comment] 2017-09-02 06:31
At this point, the issue pertains to something within the mono platform, the long term solution lies moving server over to a .NET core implementation, though that is long off.

As for the socket shutdown, we could work around this, as I have mentioned to @da3dsoul by re-creating the socket, but as I don't know that well on how the AniDB queue system works, I'm not game enough to modify it.

**Comment by Cazzar** [comment] 2017-09-02 06:33
Also to further mention, I have since been unable to personally reproduce the issue since going to docker, though I do remember getting it sometimes when running a direct build.

**Comment by da3dsoul** [comment] 2017-10-27 05:56
I think this can be closed

**Comment by Jimmyson** [comment] 2017-10-28 04:59
We have encapsulated the issue. It doesn't stop from happening though.
I would close it, and reevaluate once Mono resolves the issue.

**Comment by Cazzar** [comment] 2017-10-28 05:00
Max is looking into a way where we can run .net natively on Linux. So I
expect soon mono will no longer be part of the issue.

**Comment by bigretromike** [comment] 2018-07-16 07:48
@Cazzar @maxpiva any updates?

**Comment by Cazzar** [comment] 2018-07-16 07:49
Stopped working on this in light of major works with netstandard

**Comment by Cazzar** [comment] 2021-01-22 05:34
No longer seems to be a problem with my server running long-term, going to mark this as resolved.

**Closed by Cazzar** 2021-01-22 05:34 UTC
Labels: By Design, In Progress
