### ISSUE TITLE
docker gets stuck on file when file is missing

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#707] opened 2018-02-06 23:33 UTC
## VERSION INFORMATION

Server Version: 3.8.3

## LOG FILE
```
[2018-02-06 15:03:44:490] Info|<>c.<.ctor>b__7_0 => SVR_AniDB_Anime.UpdateStatsByAnimeID => SVR_AnimeSeries.UpdateStats Starting Updating STATS for SERIES 329 (True - True - False)
[2018-02-06 15:09:06:610] Error|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Error could not find the original file for renaming, or it is in use: /import put.io/[AnimeRG] Naruto Shippuden (Complete Series 001-500) Naruto Shippuuden [1080p] [HEVC] [x265] [Batch] [pseudo]/Season 15 (Episodes 321-348)/[AnimeRG] Naruto Shippuden - 342 [1080p] [x265] [pseudo].mkv
```
last line repeated many times

## DESCRIPTION

The file was missing since shoko had moved it but failed to handle it correctly. 
It was stuck at trying to find the file on anidb for atleast 7 hours recorded. 
Every file that was missing got stuck like that untill i either paused the queue or restarted the docker container/server.
Ofc pausing and removing missing fixed the issue, but it shouldnt have been stuck in the first place.

## STEPS TO REPRODUCE

have a missing file that shoko tries to search for on anidb (docker only? unknown)

**Comment by Cazzar** [comment] 2018-02-07 01:41
As I mentioned in discord a few days ago, it can sometimes deadlock.
Restarting will fix it.

**Comment by da3dsoul** [comment] 2018-02-07 01:43
I thought @bond4u fixed that

**Comment by Cazzar** [comment] 2018-02-07 01:44
It's reoccured recently..

**Comment by CuddleBear92** [comment] 2018-02-07 01:54
Sometimes deadlockes? Happens all the time for me. Mostly cause of issues it made itself or was made cause of restarts. 

Mostly down to database errors and mono errors and socket connection error. But yeah. Restarting does work, if it knows the files has moved. So I guess I got to remove missing each time I restart it. That's fine, but can't babysit it in my sleep sadly.

**Comment by ElementalCrisis** [comment] 2018-02-07 10:24
@Cazzar is this still caused by Mono?

**Comment by CuddleBear92** [comment] 2018-02-07 11:15
seems i might have been on the latest image instead of daily. was a left from before there was multiple choices.

have had much less issues cause of this obviously. unsure if this is still an issue. need to check somehow.

**Comment by ElementalCrisis** [comment] 2022-08-05 18:57
This issue is 4 years old and as far as I'm aware, we haven't had any more reports so gonna close this issue.

**Closed by ElementalCrisis** 2022-08-05 18:57 UTC
Labels: Help Wanted, In Progress
