### ISSUE TITLE
Series after being recognized aren't move from source to destination folder.

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#678] opened 2017-09-15 12:15 UTC
After scanning source folder (non folder is set as being watched), recognized series are being move to destination folder.
Some of there aren't moved, and some of those that aren't move ARE indeed recognized because when I remove source folder from import folder the "Delete from MyList: xxxxxx-1" command is issued few times (or many times if big series was there but wasn't moved).

So times scanning folder 2-3 times help shoko to force it to move them out, but usually after 3 scans if files aren't moved they stay there.

Series that aren't moved don't have any pattern (some are one files series, so are longer, some of them are specials, others are dramas, they are in first folder, second or even third folder inside)

Currently after adding more than 2000 series i get about ~5-10 series (from 1 file serie to 24eps) that wasn't moved.

Edit: also I noticed that some of those files are from same series that did get moved. Like now Im looking at `aoharu x kikanjuu` ep 10. crc/size compared with anidb tells me that this file is from proper release. But file dont want to move.

**Comment by da3dsoul** [comment] 2017-09-15 15:13
I'm reopening this, because I have reproduced it, but it's rare.

**Comment by da3dsoul** [comment] 2017-12-09 23:40
I've not seen this in a while. I'll close it again for now. We shall see

**Closed by da3dsoul** 2017-12-09 23:40 UTC
Labels: Bug - Minor
