### ISSUE TITLE
InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#900] opened 2021-09-21 20:27 UTC
## VERSION INFORMATION

Server Version: 4.1.0
Web UI Version:  1.1.1-dev2
Desktop Version:  4.1.0

```
[2021-09-21 13:20:46:658] Error|<>c.<Configure>b__9_0 => AsyncMethodBuilderCore.Start => <<Configure>b__9_0>d.MoveNext System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Shoko.Server.API.v2.Models.core.APIMessage.ExecuteResult(ActionContext context) in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\v2\Models\core\APIMessage.cs:line 66
   at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Shoko.Server.API.Startup.<>c.<<Configure>b__9_0>d.MoveNext() in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\Startup.cs:line 191
```

## DESCRIPTION

When running the "Sync Plex Watch Status" action, it generates this error. 

## STEPS TO REPRODUCE

Run "Sync Plex Watch Status" action.

**Comment by Cazzar** [comment] 2021-09-26 15:23
Updated the title as it isn't a specific thing to SyncWatchStatus.

I think as this point we just need to remove all instances of ApiStatus<T> and just return the ASP version instead of the hacky wrapper.

**Comment by Cazzar** [comment] 2021-09-26 15:41
Duplicate of #882

**Closed by Cazzar** 2021-09-26 15:41 UTC
Labels: Bug - Minor
